### ISSUE TITLE
Something else I just discovered... 

### ISSUE THREAD

**Issue by nijel8** [zhaochengw/android_device_xiaomi_hydrogen#2]
At xda we just discovered Mi Max has two different hw variations:

EMMC: Toshiba
DDR: Samsung
LCD: TIANMA FHD R63350 VIDEO PANEL
TOUCH IC: Focaltech
TP Maker: Ofilm

and

EMMC: Samsung
DDR: Elpida
LCD: AUO FHD R61322 VIDEO PANEL
TOUCH IC: Atmel
TP Maker: Biel D1

These needs to be accounted for for example for dt2w to work for both and other hw dependant features as welll. See http://forum.xda-developers.com/showpost.php?p=69473153&postcount=1423

**Comment by nijel8** [comment]
Auo display result:

shell: find /sys/devices/soc.0 -name wakeup_mode
/sys/devices/soc.0/78b8000.i2c/i2c-4/4-004a/wakeup_mode

So it is in the other 4-00.. folder for amtel TP.

**Comment by zhaochengw** [comment]
OK
have doen to fix dt2w on different touch screen
need more test

**Comment by nijel8** [comment]
Looks good to me... 
Just curious to see how Xiaomi do it in miui... Will look at it if/when get a chance.
